parameters:
  targetFramework: ''

steps:
- task: CopyFiles@2
  condition: and(succeeded(), ne(variables.Build.Reason, 'PullRequest'))
  displayName: 'Artifacts: Pack: ${{parameters.targetFramework}}'
  continueOnError: true
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/bin/**/${{parameters.targetFramework}}/!(xunit.*|System.*|Microsoft.*|*.Tests.dll|*.pdb)'
    targetFolder: '$(Build.ArtifactStagingDirectory)/${{parameters.targetFramework}}'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), ne(variables.Build.Reason, 'PullRequest'))
  displayName: 'Artifacts: Publish: ${{parameters.targetFramework}}'
  continueOnError: true
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/${{parameters.targetFramework}}'
    artifactName: '$(artifactPrefix)${{parameters.targetFramework}}$(artifactSuffix)'
    publishLocation: 'Container'
