# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

name: '$(Date:yy.MM.dd)$(Rev:.rr)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PowerShell@2
  inputs:
    filePath: 'azure-pipelines-prebuild.ps1'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Create and "publish" main artifact.
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/bin/**/!(Microsoft.*|*.Tests.dll|*.pdb|*.config)'
    targetFolder: '$(Build.ArtifactStagingDirectory)/main'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/main'
    artifactName: 'main'
    publishLocation: 'Container'

# Create and "publish" nupkg artifacts.
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'MonoMod@(|.Utils|.RuntimeDetour)/*.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)/nupkgs'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nupkgs'
    artifactName: 'nupkgs'
    publishLocation: 'Container'
