strategy:
  matrix:
    windows:
      jobArchName: 'Windows'
      imageName: 'windows-2019'
      artifactPrefix: ''
      artifactSuffix: ''
      builder: 'core'
      testers: ';fx;core2;'
      coreVersion: ''
      generateDocFX: 'true'
    linux-core:
      jobArchName: 'Linux .NET Core'
      imageName: 'ubuntu-16.04'
      artifactPrefix: '~dbg/linux-core/'
      artifactSuffix: ''
      builder: 'core'
      testers: ';core2;'
      coreVersion: '2.1.x'
      generateDocFX: 'false'
    linux-mono:
      jobArchName: 'Linux Mono'
      imageName: 'ubuntu-16.04'
      artifactPrefix: '~dbg/linux-mono/'
      artifactSuffix: ''
      builder: 'mono'
      testers: ';mono;'
      coreVersion: '2.1.x'
      generateDocFX: 'false'
    macos:
      jobArchName: 'macOS'
      imageName: 'macOS-10.14'
      artifactPrefix: '~dbg/macos-core/'
      artifactSuffix: ''
      builder: 'core'
      testers: ';mono;core2;'
      coreVersion: '2.1.x'
      generateDocFX: 'false'
  maxParallel: 4

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'
  xunit: '{0}{1}/.nuget/packages/xunit.runner.console/2.4.1/tools/{2}/xunit.console.{3} MonoMod.UnitTest/bin/Release/{2}/MonoMod.UnitTest.dll -xml testresults.{4}.{2}.xml'

name: '$(Date:yy.MM.dd)$(Rev:.rr)'

pool:
  vmImage: '$(imageName)'

steps:
- checkout: self 
  clean: false
  fetchDepth: 1
  lfs: false
  submodules: recursive

# Run pre-build steps.
- task: UseDotNet@2
  condition: and(succeeded(), ne(variables.coreVersion, ''))
  displayName: 'Update .NET Core SDK'
  inputs:
    packageType: sdk
    version: '$(coreVersion)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet: Restore'
  inputs:
    command: 'restore'
    projects: 'MonoMod*/*.csproj'

# Build using core.
- task: DotNetCoreCLI@2
  condition: and(succeeded(), eq(variables.builder, 'core'))
  displayName: 'dotnet: Build'
  inputs:
    command: 'build'
    projects: 'MonoMod*/*.csproj'
    arguments: '--configuration $(buildConfiguration) "/p:Configuration=$(buildConfiguration)"'
# Build using mono.
- task: CmdLine@2
  condition: and(succeeded(), eq(variables.builder, 'mono'))
  displayName: 'mono: Build'
  inputs:
    script: 'msbuild MonoMod.sln "/p:Configuration=$(buildConfiguration)" "/p:Platform=$(buildPlatform)"'

# Create and "publish" main artifacts.
- template: 'azure-pipelines-postbuild.yml'
  parameters:
    targetFramework: 'net35'
- template: 'azure-pipelines-postbuild.yml'
  parameters:
    targetFramework: 'netstandard2.0'

# Create and "publish" nupkg artifacts.
- task: DotNetCoreCLI@2
  condition: and(succeeded(), ne(variables.Build.Reason, 'PullRequest'))
  displayName: 'Artifacts: Pack: nupkgs'
  continueOnError: true
  inputs:
    command: 'pack'
    nobuild: true
    configuration: '$(buildConfiguration)'
    versioningScheme: 'byBuildNumber'
    packagesToPack: 'MonoMod@(|.Utils|.RuntimeDetour|.RuntimeDetour.HookGen)/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/nupkgs'
- task: PublishBuildArtifacts@1
  condition: and(succeeded(), ne(variables.Build.Reason, 'PullRequest'))
  displayName: 'Artifacts: Publish: nupkgs'
  continueOnError: true
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/nupkgs'
    artifactName: '$(artifactPrefix)nupkgs$(artifactSuffix)'
    publishLocation: 'Container'

# Run tests.
# I've tried to simplify this mess. It's impossible. --ade
- task: CmdLine@2
  condition: and(always(), contains(variables.testers, ';fx;'))
  displayName: 'Test: fx: net452'
  inputs:
    script: ${{format(variables.xunit, '', '%userprofile%', 'net452', 'exe', 'fx')}}
- task: PublishTestResults@2
  condition: and(always(), contains(variables.testers, ';fx;'))
  displayName: 'Test: Publish: fx: net452'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/testresults.fx.net452.xml'
    testRunTitle: 'Tests @ $(jobArchName) fx net452'

- task: CmdLine@2
  condition: and(always(), contains(variables.testers, ';mono;'))
  displayName: 'Test: mono: net452'
  inputs:
    script: ${{format(variables.xunit, 'mono --debug ', '~', 'net452', 'exe', 'mono')}}
- task: PublishTestResults@2
  condition: and(always(), contains(variables.testers, ';mono;'))
  displayName: 'Test: Publish: mono: net452'
  inputs:
    testResultsFormat: 'xUnit'
    testResultsFiles: '**/testresults.mono.net452.xml'
    testRunTitle: 'Tests @ $(jobArchName) mono net452'

- task: CmdLine@2
  condition: and(always(), contains(variables.testers, ';core2;'))
  displayName: 'Test: core: netcoreapp2.0'
  inputs:
    script: 'dotnet test --no-build --configuration ${{variables.buildConfiguration}} -f netcoreapp2.0 MonoMod.UnitTest/MonoMod.UnitTest.csproj -l:"trx;LogFileName=testresults.core.netcoreapp2.0.trx"'
- task: PublishTestResults@2
  condition: and(always(), contains(variables.testers, ';core2;'))
  displayName: 'Test: Publish: core: netcoreapp2.0'
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/testresults.core.netcoreapp2.0.trx'
    testRunTitle: 'Tests @ $(jobArchName) core netcoreapp2.0'

# Create and "publish" nupkg artifacts.
- task: PowerShell@2
  condition: and(always(), ne(variables.Build.Reason, 'PullRequest'), eq(variables.generateDocFX, 'true'))
  displayName: 'DocFX'
  continueOnError: true
  inputs:
    filePath: 'azure-pipelines-docfx.ps1'
    arguments: '$(GitHubBotName) $(GitHubBotEmail) $(GitHubBotToken)'
