parameters:
  targetFramework: ''

steps:
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Agent.BuildDirectory)'
    contents: '**/bin/**/${{parameters.targetFramework}}/!(xunit.*|System.*|Microsoft.*|*.Tests.dll|*.pdb)'
    targetFolder: '$(Build.ArtifactStagingDirectory)/${{parameters.targetFramework}}'
    cleanTargetFolder: true
    overWrite: true
    flattenFolders: true
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/${{parameters.targetFramework}}'
    artifactName: '${{parameters.targetFramework}}'
    publishLocation: 'Container'
